### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when processing module-info.java

### ISSUE THREAD

**Issue by aalmiray** [bmuschko/gradle-java2html-plugin#4]
It appears that the latest version of `com.bmuschko.gradle.java2html.GenerateOverviewTask` can't handle source files that define no package. 

Source file structure

    subprojects/ikonli-core/src/main/java/
    ├── module-info.java
    └── org
        └── kordamp
            └── ikonli
                ├── AbstractIkonHandler.java
                ├── Ikon.java
                ├── IkonHandler.java
                ├── Ikonli.java
                └── IkonliIkonResolver.java

Converted source file structure looks like this

    subprojects/ikonli-core/build/tmp/source-html/
    ├── conversion
    │   ├── module-info.html
    │   └── org
    │       └── kordamp
    │           └── ikonli
    │               ├── AbstractIkonHandler.html
    │               ├── Ikon.html
    │               ├── IkonHandler.html
    │               ├── Ikonli.html
    │               └── IkonliIkonResolver.html
    └── overview
        ├── module-info.html
        └── org
            └── kordamp
                └── ikonli
                    ├── AbstractIkonHandler.html
                    ├── Ikon.html
                    ├── IkonHandler.html
                    ├── Ikonli.html
                    └── IkonliIkonResolver.html

Stacktrace:

    Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 16
            at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
            at java.base/java.lang.String.substring(String.java:1874)
            at java_lang_String$substring$9.call(Unknown Source)
            at com.bmuschko.gradle.java2html.internal.DocMetaDataExtractor$_getPackages_closure2.doCall(DocMetaDataExtractor.groovy:61)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
            at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
            at groovy.lang.Closure.call(Closure.java:418)
            at groovy.lang.Closure.call(Closure.java:434)
            at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
            at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
            at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
            at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
            at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
            at com.bmuschko.gradle.java2html.internal.DocMetaDataExtractor.getPackages(DocMetaDataExtractor.groovy:59)
            at com.bmuschko.gradle.java2html.internal.DocMetaDataExtractor$getPackages.call(Unknown Source)
            at com.bmuschko.gradle.java2html.internal.Java2HTMLDocGenerator.generate(Java2HTMLDocGenerator.groovy:50)
            at com.bmuschko.gradle.java2html.internal.Java2HTMLDocGenerator$generate.call(Unknown Source)
            at com.bmuschko.gradle.java2html.GenerateOverviewTask.start(GenerateOverviewTask.groovy:56)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)

Exception occurs at https://github.com/bmuschko/gradle-java2html-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/java2html/internal/DocMetaDataExtractor.groovy#L61

Environment:

    ------------------------------------------------------------
    Gradle 4.10.2
    ------------------------------------------------------------

    Build time:   2018-09-19 18:10:15 UTC
    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

    Kotlin DSL:   1.0-rc-6
    Kotlin:       1.2.61
    Groovy:       2.4.15
    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
    JVM:          11 (Oracle Corporation 11+28)
    OS:           Mac OS X 10.13.6 x86_64

**Comment by bmuschko** [comment]
It has been released.
